var svg = d3.select("body").append("svg")

svg.append("circle")
  .attr("cx", 20)
  .attr("cy", 20)
  .attr("r", 10)
  .style("fill", "gray")
  .transition()
    .delay(300)
    .duration(700)
    .attr("cx", 150)
    .attr("cy", 100)
    .attr("r", 40)
    .style("fill", "#FFC000")
    .transition()
      .duration(1000)
      .attr("cx", 130)
      .attr("cy", 250)
      .attr("r", 20)
      .style("fill", "red")
      .attr("opacity", 1)
      .transition()
        .duration(1000)
        .attr("opacity", 0)
        .remove()
